### ISSUE TITLE
add transaction fee estimation to reports (if needed)

### ISSUE THREAD

**Issue by landonshumway-ia** [csg-org/CompactConnect#524]
Initially, as part of reporting we were going to include a row in the financial summary report to show an estimate of how much would be collected by transaction fees for the given period. This was under the assumption that each compact would be using Authorize.net's default Merchant Service Provider (MSP). This turned out to be inaccurate, as at least one compact is using a separate MSP, which leads to complications in determining an estimate since Authorize.net includes additional batch processing fees when not using their default MSP.

This ticket was created for us to revisit this feature and determine if it is necessary to include transaction fee estimates as part of the financial summary report.

**Comment by landonshumway-ia** [comment]
Capturing this detail here for future reference:

- Our initial design to support this was to include a 'processorFees' section to the compact onboarding configuration files, under the 'transactionFeeConfiguration' section:
```
transactionFeeConfiguration:
    processorFees: 
        percentageRate: 2.9  
        fixedRatePerTransaction: 0.30
```
